name: Build Android App
 
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Change to your desired Java version

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
        env:
          API_KEY: ${{ secrets.API_KEY }} # Add your secret if needed

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
          
